var messagesEN = {
	LabNoNetworkConnectivity : "You have no network connectivity to the TV - Please check the settings on the TV",
	LabEnterIP : "Enter the IP address & port number of your Jellyfin server. <br>(You can leave the port blank for 8096)",
	LabOr : "OR",
	LabEnterHost : "Enter your server hostname here without http:// and <br>including : and port number.",
	LabPleaseWait : "Please Wait",
	LabCheckDetails : "Checking Details",
	LabPleaseReenter : "Please re-enter your server details.",
	LabIncorDetails : "Incorrect Details",
	LabButtonReturn : "Return",
	LabButtonExit : "Exit",
	LabButtonDefault : "Default",
	LabButtonDelete : "Delete",
	LabButtonDelUsers : "Del All users",
	LabButtonDelPass : "Del All passwords",
	LabButtonFavourite : "Favourite",
	LabButtonWatched : "Watched",
	LabButtonHelp : "Help",
	LabButtonMusic : "Music",
	LabButtonNextIndex : "Next Index  ",
	LabHelpPage : "Help Page",
	LabHelpImagePlayer : "Return, Stop - Ends slideshow and returns the user to the previous screen. <br> " +
	"Left, Right - Move 1 image backwards or forwards. <br>" +
	"Pause - Pause slideshow. <br>" +
	"Play - Resume slideshow. <br>" +
	"Red - Mark photo as a favourite. <br>" +
	"Green - Toggle Date/Time overlay; None | Date | Date : Time <br>" +
	"Yellow - Show this help message. <br>" +
	"Blue - When music is playing, show the music player controls. ",
	LabHelpOtherPlayer : "Tools - Show the main menu. <br> " +
	"Return - Returns the user to the previous screen. <br> " +
	"Up, Down, Left, Right - Navigation Control. <br>" +
	"Enter - Select the highlighted item. <br>" +
	"Red - Add or remove an item on the favourites page. <br>" +
	"Green - Mark a video item as watched or unwatched. <br>" +
	"Yellow - Show this help message. <br>" +
	"Blue - When music is playing, show the music player controls. <br>" +
	"Ch. Up/Down - Skips one page of content. ",
	LabPassword : "Password",
	LabUserName : "Username",
	LabRememberPassword : "Remember",
	LabManualLogin : "Login manually",
	LabChangeServer : "Change Server",
	LabUsersDescription : "Available options for each page are shown at the bottom.<br>Once logged in, move left on any page to access the main menu.",
	LabServersDescription : "<p style='margin-top:15px'>Use the <span style='color: red'>A</span> button to set the selected server as the default auto connect server</p><p>Use the <span style='color: #2ad'>D</span> button to delete the selected server</p>",
	LabAddNewServer : "Add a New Server",
	LabYes : "yes",
	LabNo : "no",
	LabNetworkStatus : "Network Status",
	LabNetworkError : "Network Error",
	LabServerError : "Server Error",
	LabBadPassword : "Bad password or network error.",
	LabLogonError : "Logon Error",
	LabDeletion : "Deletion",
	LabDelAllPass : "All Passwords Deleted",
	LabDelAllUser : "All Users Deleted",
	LabBadRequest : "Bad xmlHTTP Request<br>Token : ",
	LabHTTPStatus : "The HTTP status code returned by the server was : ",
	LabJellefinCon : "Jellyfin server connection error.<br>Status : ",
	LabJellefinRes : "Your Jellyfin server is not responding.<br>Status : ",
	LabServerChangeTxt : " is now your default Server and will be logged in autiomatically from now on.", 
	LabServerChange : "Default Server Changed",
	LabServerVersion : "The Samsung app requires a later version of the Server - Please update it and restart the app",
	LabBadPass : "Wrong username, bad password or network error.",
	LabHome : "Home",
	LabFavourites : "Favourites",
	LabTVShows : "TVShows",
	LabHomeMovies : "Home Movies",
	LabCollections : "Collections",
	LabMovies : "Movies",
	LabPhotos : "Photos",
	LabMusic : "Music",
	LabPlaylists : "Playlists",
	LabLiveTV : "Live TV",
	LabChannels : "Channels",
	LabMediaFolders : "Media Folders",
	LabSearch : "Search",
	LabSettings : "Settings",
	LabLogOut : "LogOut",
	LabLatestMovies : "Latest Movies",
	LabButtonFullScreen : "Full Screen",
	LabRESUME : "RESUME",
	LabPLAYTRAILER : "PLAY TRAILER",
	LabPLAY : "PLAY",
	LabCHAPTERS : "CHAPTERS",
	LabMOREEPISODES : "MORE EPISODES",
	LabCAST : "CAST",
	LabADDTOPLAYLIST : "ADD TO PLAYLIST",
	LabSUGGESTED : "SUGGESTED",
};